import React, { useState, useEffect, useRef } from 'react';
import { Resource, ResourceCategory, CATEGORY_JP } from '../types';
import { getResources, saveResource, deleteResource, updateResource } from '../data/resources';

const AdminDashboard: React.FC<{ onLogout: () => void }> = ({ onLogout }) => {
  const [resources, setResources] = useState<Resource[]>([]);
  const [activeTab, setActiveTab] = useState<'stats' | 'add' | 'manage'>('stats');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showDeployModal, setShowDeployModal] = useState(false);
  
  // Link Toggles
  const [showYoutube, setShowYoutube] = useState(false);
  const [showDrive, setShowDrive] = useState(false);
  const [showKey, setShowKey] = useState(false);
  const [showDownload, setShowDownload] = useState(true);

  // Form State
  const [formData, setFormData] = useState<Partial<Resource>>({
    category: ResourceCategory.SOFTWARE
  });
  const [isCategoryOpen, setIsCategoryOpen] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const categoryRef = useRef<HTMLDivElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setResources(getResources());
    const handleClickOutside = (e: MouseEvent) => {
      if (categoryRef.current && !categoryRef.current.contains(e.target as Node)) {
        setIsCategoryOpen(false);
      }
    };
    window.addEventListener('mousedown', handleClickOutside);
    return () => window.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const resetForm = () => {
    setFormData({ category: ResourceCategory.SOFTWARE });
    setEditingId(null);
    setShowYoutube(false);
    setShowDrive(false);
    setShowKey(false);
    setShowDownload(true);
    setFormError(null);
  };

  const startEdit = (resource: Resource) => {
    setEditingId(resource.id);
    setFormData(resource);
    setShowYoutube(!!resource.youtubeId);
    setShowDrive(!!resource.driveUrl);
    setShowKey(!!resource.getKeyUrl);
    setShowDownload(!!resource.downloadUrl);
    setActiveTab('add');
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);

    if (!formData.name || !formData.description || !formData.thumbnail) {
      setFormError('CRITICAL: BASIC_METADATA_MISSING');
      return;
    }

    const hasActiveLink = 
      (showDownload && formData.downloadUrl?.trim()) || 
      (showYoutube && formData.youtubeId?.trim()) || 
      (showDrive && formData.driveUrl?.trim()) || 
      (showKey && formData.getKeyUrl?.trim());

    if (!hasActiveLink) {
      setFormError('FAILURE: NO_ACTIVE_ACCESS_ENDPOINT');
      return;
    }

    setIsSubmitting(true);
    
    setTimeout(() => {
      const dataToSave: Resource = {
        ...formData as Resource,
        id: editingId || `res-${Date.now()}`,
        createdAt: formData.createdAt || Date.now()
      };
      
      if (!showYoutube) delete dataToSave.youtubeId;
      if (!showDrive) delete dataToSave.driveUrl;
      if (!showKey) delete dataToSave.getKeyUrl;
      if (!showDownload) delete dataToSave.downloadUrl;

      let updated;
      if (editingId) {
        updated = updateResource(dataToSave);
      } else {
        updated = saveResource(dataToSave);
      }
      
      setResources(updated);
      setIsSubmitting(false);
      setActiveTab('manage');
      resetForm();
    }, 1000);
  };

  const handleDelete = (id: string) => {
    if (confirm('DANGER: DELETE FROM ARCHIVE PERMANENTLY?')) {
      const updated = deleteResource(id);
      setResources(updated);
    }
  };

  const generateDeploymentCode = () => {
    const resourcesJson = JSON.stringify(resources, null, 2);
    return `import { Resource, ResourceCategory } from '../types';

/**
 * PRODUCTION ARCHIVE DATA
 * Auto-generated by Resource Forensic Admin Panel
 * Note: 'as any' is used to satisfy TS when enum values are literals in JSON.
 */
const INITIAL_RESOURCES: Resource[] = ${resourcesJson} as any;

const STORAGE_KEY = 'resource_forensic_vault';

export const getResources = (): Resource[] => {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (!stored) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(INITIAL_RESOURCES));
    return INITIAL_RESOURCES;
  }
  return JSON.parse(stored);
};

export const saveResource = (resource: Resource) => {
  const resources = getResources();
  const updated = [resource, ...resources];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
};

export const updateResource = (updatedResource: Resource) => {
  const resources = getResources();
  const updated = resources.map(r => r.id === updatedResource.id ? updatedResource : r);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
};

export const deleteResource = (id: string) => {
  const resources = getResources();
  const updated = resources.filter(r => r.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
};
`;
  };

  const copyDeploymentCode = () => {
    const code = generateDeploymentCode();
    navigator.clipboard.writeText(code);
    alert('CODE_COPIED: Replace the content of data/resources.ts with this code. Commit and Push to GitHub to update globally.');
  };

  const exportArchive = () => {
    const dataStr = JSON.stringify(resources, null, 2);
    const dataUri = 'data:application/json;charset=utf-8,'+ encodeURIComponent(dataStr);
    const exportFileDefaultName = `resource_forensic_archive_${new Date().toISOString().split('T')[0]}.json`;
    const linkElement = document.createElement('a');
    linkElement.setAttribute('href', dataUri);
    linkElement.setAttribute('download', exportFileDefaultName);
    linkElement.click();
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      try {
        const importedData = JSON.parse(event.target?.result as string);
        if (Array.isArray(importedData)) {
          if (confirm(`RESTORE_PROTOCOL: THIS WILL OVERWRITE ${resources.length} EXISTING ENTRIES WITH ${importedData.length} NEW ENTRIES. PROCEED?`)) {
            localStorage.setItem('resource_forensic_vault', JSON.stringify(importedData));
            setResources(importedData);
          }
        }
      } catch (err) {
        alert('FAILURE: ARCHIVE_CORRUPTION_DETECTED');
      }
    };
    reader.readAsText(file);
  };

  const categories = Object.values(ResourceCategory);
  const statsByCategory = categories.map(cat => ({
    name: cat,
    count: resources.filter(r => r.category === cat).length
  }));
  const maxCount = Math.max(...statsByCategory.map(s => s.count), 1);

  return (
    <div className="min-h-screen bg-[#050505] text-white p-4 md:p-12 font-mono selection:bg-white selection:text-black relative overflow-x-hidden">
      <div className="max-w-6xl mx-auto relative z-10">
        
        {/* Terminal Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-end mb-10 md:mb-16 gap-6 border-b border-white/5 pb-8">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <div className="w-2 h-2 bg-red-600 rounded-full animate-pulse shadow-[0_0_8px_rgba(220,38,38,0.5)]" />
              <h1 className="text-base md:text-xl font-black tracking-[0.4em] uppercase">Control_Center</h1>
            </div>
            <p className="text-[8px] md:text-[9px] opacity-20 tracking-[0.2em] uppercase font-black">Archive_Index_v9.1 // GitHub_Sync: Ready</p>
          </div>
          <div className="flex items-center gap-6 md:gap-10 overflow-x-auto no-scrollbar w-full md:w-auto pb-2 md:pb-0">
             <button onClick={() => { setActiveTab('stats'); resetForm(); }} className={`text-[8px] md:text-[9px] tracking-[0.3em] md:tracking-[0.4em] uppercase font-black transition-all whitespace-nowrap ${activeTab === 'stats' ? 'opacity-100' : 'opacity-20 hover:opacity-50'}`}>Telemetry</button>
             <button onClick={() => setActiveTab('add')} className={`text-[8px] md:text-[9px] tracking-[0.3em] md:tracking-[0.4em] uppercase font-black transition-all whitespace-nowrap ${activeTab === 'add' ? 'opacity-100' : 'opacity-20 hover:opacity-50'}`}>
                {editingId ? 'Maintenance' : 'Ingestion'}
             </button>
             <button onClick={() => { setActiveTab('manage'); resetForm(); }} className={`text-[8px] md:text-[9px] tracking-[0.3em] md:tracking-[0.4em] uppercase font-black transition-all whitespace-nowrap ${activeTab === 'manage' ? 'opacity-100' : 'opacity-20 hover:opacity-50'}`}>Registry</button>
             <div className="hidden md:block w-[1px] h-4 bg-white/10" />
             <button onClick={onLogout} className="text-[8px] md:text-[9px] tracking-[0.3em] md:tracking-[0.4em] uppercase font-black opacity-30 hover:opacity-100 hover:text-red-500 transition-all border border-white/5 px-3 md:px-4 py-1.5 whitespace-nowrap">Sign_Out</button>
          </div>
        </div>

        {/* Views */}
        <div className="animate-in fade-in duration-500">
          {activeTab === 'stats' && (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 md:gap-8">
               <div className="md:col-span-2 border border-white/5 bg-white/[0.01] p-6 md:p-10 h-[30rem] md:h-80 relative overflow-hidden group">
                  <div className="absolute inset-0 opacity-[0.02] bg-[length:24px_24px] [background-image:linear-gradient(to_right,white_1px,transparent_1px),linear-gradient(to_bottom,white_1px,transparent_1px)]" />
                  <div className="relative z-10 h-full flex flex-col">
                     <span className="text-[8px] opacity-20 tracking-widest uppercase mb-auto font-black">Archive_Distribution_Map</span>
                     <div className="flex items-end gap-3 md:gap-6 h-48 mt-8">
                        {statsByCategory.map(s => (
                           <div key={s.name} className="flex-1 flex flex-col items-center group/bar">
                              <div 
                                className="w-full bg-white/5 group-hover/bar:bg-white/20 transition-all duration-1000 border-t border-x border-white/10"
                                style={{ height: `${(s.count / maxCount) * 100}%` }}
                              />
                              <span className="text-[6px] md:text-[7px] opacity-20 mt-3 vertical-text uppercase tracking-[0.3em] md:tracking-[0.4em] font-black h-16 md:h-20 transition-all group-hover/bar:opacity-100 whitespace-nowrap">{s.name}</span>
                           </div>
                        ))}
                     </div>
                  </div>
               </div>
               <div className="space-y-6">
                  <div className="border border-white/5 bg-white/[0.02] p-6 md:p-8 group">
                     <span className="text-[8px] opacity-20 tracking-widest uppercase font-black">Archive_Count</span>
                     <div className="text-4xl md:text-6xl font-black mt-2 tracking-tighter group-hover:scale-[1.02] transition-transform">{resources.length}</div>
                  </div>
                  <div className="border border-white/5 bg-white/[0.02] p-6 md:p-8 group">
                     <span className="text-[8px] opacity-20 tracking-widest uppercase font-black">Security_Status</span>
                     <div className="text-2xl md:text-3xl font-black mt-2 tracking-tighter text-green-500/60">NOMINAL</div>
                  </div>
               </div>
            </div>
          )}

          {activeTab === 'add' && (
            <form onSubmit={handleSubmit} className="max-w-4xl mx-auto space-y-8 md:space-y-12 pb-32">
              {editingId && (
                <div className="flex items-center justify-between p-4 border border-blue-500/20 bg-blue-500/5 rounded-sm">
                   <div className="flex items-center gap-3">
                      <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />
                      <span className="text-[10px] tracking-[0.3em] font-black uppercase text-blue-400">MAINTENANCE_MODE_ACTIVE // EDITING: {editingId}</span>
                   </div>
                   <button 
                    type="button" 
                    onClick={resetForm}
                    className="text-[8px] tracking-[0.2em] uppercase font-black opacity-40 hover:opacity-100 underline"
                   >
                     ABORT_MAINTENANCE
                   </button>
                </div>
              )}

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-10">
                <div className="space-y-3">
                  <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-30 font-black ml-1">Asset_Name</label>
                  <input 
                    required 
                    className="w-full bg-white/[0.03] border border-white/10 p-4 md:p-5 text-sm focus:border-white/40 outline-none transition-all placeholder:opacity-10 tracking-[0.1em] text-white"
                    placeholder="ENTER_ITEM_TITLE"
                    value={formData.name || ''}
                    onChange={e => setFormData({...formData, name: e.target.value})}
                  />
                </div>

                <div className="space-y-3" ref={categoryRef}>
                  <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-30 font-black ml-1">Archive_Sector</label>
                  <div className="relative">
                    <button 
                      type="button"
                      onClick={() => setIsCategoryOpen(!isCategoryOpen)}
                      className="w-full bg-white/[0.03] border border-white/10 p-4 md:p-5 text-sm text-left focus:border-white/40 outline-none transition-all uppercase tracking-[0.2em] flex justify-between items-center"
                    >
                      {formData.category}
                      <svg className={`w-4 h-4 transition-transform duration-300 ${isCategoryOpen ? 'rotate-180' : 'rotate-0'}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={3}><path d="M19 9l-7 7-7-7"/></svg>
                    </button>
                    {isCategoryOpen && (
                      <div className="absolute z-50 top-full left-0 w-full mt-2 bg-[#0a0a0a] border border-white/20 shadow-2xl max-h-72 overflow-y-auto no-scrollbar">
                        {categories.map(cat => (
                          <button
                            key={cat}
                            type="button"
                            onClick={() => {
                              setFormData({...formData, category: cat});
                              setIsCategoryOpen(false);
                            }}
                            className="w-full text-left p-5 text-[11px] tracking-[0.2em] uppercase hover:bg-white hover:text-black transition-colors font-bold"
                          >
                            {cat}
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>

              <div className="space-y-3">
                <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-30 font-black ml-1">Data_Background</label>
                <textarea 
                  required 
                  className="w-full bg-white/[0.03] border border-white/10 p-4 md:p-5 text-sm focus:border-white/40 outline-none transition-all h-32 tracking-widest placeholder:opacity-10 resize-none"
                  placeholder="METADATA_DESCRIPTION_FOR_ARCHIVE..."
                  value={formData.description || ''}
                  onChange={e => setFormData({...formData, description: e.target.value})}
                />
              </div>

              <div className="space-y-3">
                <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-30 font-black ml-1">Cover_Thumbnail_Source</label>
                <input 
                  required 
                  className="w-full bg-white/[0.03] border border-white/10 p-4 md:p-5 text-sm focus:border-white/40 outline-none transition-all tracking-[0.1em]"
                  placeholder="HTTPS://IMAGE_ENDPOINT_URL"
                  value={formData.thumbnail || ''}
                  onChange={e => setFormData({...formData, thumbnail: e.target.value})}
                />
              </div>

              <div className="pt-8 border-t border-white/5 space-y-8">
                 <div className="flex flex-col gap-3">
                    <span className="text-[8px] uppercase tracking-[0.4em] md:tracking-[0.6em] opacity-20 font-black mb-2">Endpoint_Configuration</span>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                      {[
                        { id: 'dl', label: 'Download_Link', state: showDownload, set: setShowDownload },
                        { id: 'yt', label: 'YouTube_Embed', state: showYoutube, set: setShowYoutube },
                        { id: 'dr', label: 'Drive_Source', state: showDrive, set: setShowDrive },
                        { id: 'ky', label: 'Access_Protocol', state: showKey, set: setShowKey },
                      ].map(t => (
                        <button
                          key={t.id}
                          type="button"
                          onClick={() => t.set(!t.state)}
                          className={`clickable px-4 md:px-6 py-3 border text-[8px] md:text-[9px] tracking-[0.2em] md:tracking-[0.3em] font-black uppercase transition-all flex items-center gap-3 ${t.state ? 'bg-white text-black border-white' : 'opacity-20 border-white/10 hover:opacity-60'}`}
                        >
                          <div className={`w-2 h-2 rounded-full ${t.state ? 'bg-black animate-pulse' : 'bg-white/40'}`} />
                          {t.label}
                        </button>
                      ))}
                    </div>
                 </div>

                <div className="space-y-6 md:space-y-8 animate-in fade-in slide-in-from-top-4 duration-500">
                  {showDownload && (
                    <div className="space-y-3">
                      <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-40 font-black ml-1 text-white">Direct_Download_Path</label>
                      <input 
                        required={showDownload}
                        className="w-full bg-white/[0.05] border border-white/30 p-4 md:p-5 text-sm outline-none transition-all tracking-[0.1em] text-white focus:border-white"
                        placeholder="HTTPS://DIRECT_ASSET_SOURCE"
                        value={formData.downloadUrl || ''}
                        onChange={e => setFormData({...formData, downloadUrl: e.target.value})}
                      />
                    </div>
                  )}
                  {showYoutube && (
                    <div className="space-y-3">
                      <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-40 font-black ml-1 text-white">Video_Archive_ID</label>
                      <input 
                        required={showYoutube}
                        className="w-full bg-white/[0.05] border border-white/30 p-4 md:p-5 text-sm outline-none transition-all tracking-[0.1em] text-white focus:border-white"
                        placeholder="YOUTUBE_ID (e.g., dQw4w9WgXcQ)"
                        value={formData.youtubeId || ''}
                        onChange={e => setFormData({...formData, youtubeId: e.target.value})}
                      />
                    </div>
                  )}
                  {showDrive && (
                    <div className="space-y-3">
                      <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-40 font-black ml-1 text-white">Cloud_Repository_URL</label>
                      <input 
                        required={showDrive}
                        className="w-full bg-white/[0.05] border border-white/30 p-4 md:p-5 text-sm outline-none transition-all tracking-[0.1em] text-white focus:border-white"
                        placeholder="HTTPS://DRIVE_CLOUD_LINK"
                        value={formData.driveUrl || ''}
                        onChange={e => setFormData({...formData, driveUrl: e.target.value})}
                      />
                    </div>
                  )}
                  {showKey && (
                    <div className="space-y-3">
                      <label className="text-[8px] md:text-[9px] uppercase tracking-[0.3em] md:tracking-[0.5em] opacity-40 font-black ml-1 text-white">Encryption_Key_Source</label>
                      <input 
                        required={showKey}
                        className="w-full bg-white/[0.05] border border-white/30 p-4 md:p-5 text-sm outline-none transition-all tracking-[0.1em] text-white focus:border-white"
                        placeholder="HTTPS://GET_KEY_URL"
                        value={formData.getKeyUrl || ''}
                        onChange={e => setFormData({...formData, getKeyUrl: e.target.value})}
                      />
                    </div>
                  )}
                </div>
              </div>

              {formError && (
                <div className="p-4 md:p-5 border border-red-600/30 bg-red-600/5 text-red-500 text-[9px] md:text-[10px] tracking-[0.3em] md:tracking-[0.5em] font-black uppercase text-center animate-shake">
                  [ ALERT ]: {formError}
                </div>
              )}

              <div className="pt-6 md:pt-10">
                <button 
                  type="submit"
                  disabled={isSubmitting}
                  className={`clickable w-full py-6 md:py-8 font-black tracking-[0.8em] md:tracking-[1.5em] uppercase transition-all flex items-center justify-center gap-6 active:scale-[0.99] group overflow-hidden relative ${isSubmitting ? 'bg-zinc-800 text-white/50' : 'bg-white text-black hover:bg-zinc-200'}`}
                >
                  <span className="relative z-10 text-[10px] md:text-sm">{isSubmitting ? 'SECURE_TRANSMIT...' : editingId ? 'UPDATE_ARCHIVE_ENTRY' : 'COMMIT_TO_DATABASE'}</span>
                  <div className="absolute inset-0 bg-black/5 translate-y-full group-hover:translate-y-0 transition-transform duration-500" />
                </button>
              </div>
            </form>
          )}

          {activeTab === 'manage' && (
            <div className="space-y-12 pb-32">
              {/* Data Operations Panel */}
              <div className="border border-white/10 bg-white/[0.02] p-6 md:p-8 space-y-8">
                <div className="flex flex-col gap-2">
                  <div className="flex justify-between items-center">
                    <span className="text-[8px] uppercase tracking-[0.5em] opacity-30 font-black">Archive_Data_Operations</span>
                    <span className="text-[7px] opacity-10 font-black">STABILITY: OPTIMAL</span>
                  </div>
                  <div className="h-[1px] w-full bg-white/5" />
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div className="p-6 border border-white/5 bg-white/[0.01] flex flex-col gap-4">
                     <span className="text-[8px] tracking-[0.3em] opacity-40 font-black uppercase">Local_Maintenance</span>
                     <div className="flex flex-col gap-3">
                        <button 
                          onClick={exportArchive}
                          className="clickable py-3 border border-white/10 text-[8px] tracking-[0.4em] uppercase font-black hover:bg-white hover:text-black transition-all"
                        >
                          EXPORT_ARCHIVE_JSON
                        </button>
                        <button 
                          onClick={() => fileInputRef.current?.click()}
                          className="clickable py-3 border border-white/10 text-[8px] tracking-[0.4em] uppercase font-black hover:bg-white hover:text-black transition-all"
                        >
                          RESTORE_FROM_BACKUP
                        </button>
                     </div>
                  </div>

                  <div className="p-6 border border-white/10 bg-white/[0.03] flex flex-col gap-4 group">
                     <div className="flex items-center gap-2">
                        <div className="w-1.5 h-1.5 bg-blue-500 rounded-full animate-pulse" />
                        <span className="text-[8px] tracking-[0.3em] opacity-70 font-black uppercase text-blue-400">GitHub_Global_Sync</span>
                     </div>
                     <p className="text-[8px] leading-relaxed opacity-20 group-hover:opacity-40 transition-opacity">
                        To update the site for everyone on Netlify/Vercel, copy the code and push to your GitHub repository.
                     </p>
                     <button 
                        onClick={() => setShowDeployModal(true)}
                        className="clickable mt-auto py-4 bg-blue-500/10 border border-blue-500/30 text-[9px] tracking-[0.5em] uppercase font-black text-blue-400 hover:bg-blue-500 hover:text-white transition-all"
                     >
                       PREPARE_GLOBAL_DEPLOYMENT
                     </button>
                  </div>
                </div>

                <input 
                  type="file" 
                  ref={fileInputRef} 
                  className="hidden" 
                  accept=".json" 
                  onChange={handleImport}
                />
              </div>

              <div className="space-y-6">
                <div className="flex justify-between items-center px-4 md:px-6 opacity-20 text-[7px] md:text-[8px] font-black tracking-widest uppercase mb-4">
                  <span>Archive_Identifier</span>
                  <span>Operations</span>
                </div>
                {resources.length === 0 && (
                  <div className="text-center py-32 md:py-56 opacity-[0.05] text-[10px] md:text-[12px] tracking-[1.5em] md:tracking-[2em] font-black pointer-events-none select-none">NULL_DATA</div>
                )}
                {resources.map(res => (
                  <div key={res.id} className="group border border-white/5 bg-white/[0.01] hover:bg-white/[0.04] transition-all p-4 md:p-5 flex flex-col sm:flex-row justify-between items-start sm:items-center rounded-sm gap-4">
                    <div className="flex gap-4 md:gap-8 items-center w-full">
                        <div className="w-20 md:w-24 h-12 md:h-14 flex-shrink-0 border border-white/10 overflow-hidden grayscale brightness-50 group-hover:grayscale-0 group-hover:brightness-100 transition-all duration-1000">
                          <img src={res.thumbnail} className="w-full h-full object-cover scale-110 group-hover:scale-100 transition-transform duration-700" alt="" />
                        </div>
                        <div className="min-w-0">
                          <h4 className="text-[12px] md:text-[14px] font-black tracking-[0.1em] uppercase mb-1 truncate">{res.name}</h4>
                          <div className="flex flex-wrap gap-2 md:gap-4 items-center">
                            <span className="text-[7px] md:text-[8px] opacity-30 uppercase font-black tracking-widest">{res.category}</span>
                            <div className="hidden md:block w-1 h-1 bg-white/10 rounded-full" />
                            <span className="text-[7px] md:text-[8px] opacity-30 uppercase font-black tracking-widest">ID: {res.id.split('-')[1]}</span>
                          </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-2 w-full sm:w-auto">
                      <button 
                        onClick={() => startEdit(res)}
                        className="clickable flex-1 sm:flex-initial text-[8px] md:text-[9px] text-white/30 hover:text-white tracking-[0.3em] uppercase font-black transition-all p-3 md:p-4 border border-white/5 sm:border-transparent hover:border-white/10 hover:bg-white/5 text-center"
                      >
                        EDIT_DATA
                      </button>
                      <button 
                        onClick={() => handleDelete(res.id)}
                        className="clickable flex-1 sm:flex-initial text-[8px] md:text-[9px] text-red-600/30 hover:text-red-600 tracking-[0.3em] uppercase font-black transition-all p-3 md:p-4 border border-white/5 sm:border-transparent hover:border-red-600/10 hover:bg-red-600/5 text-center"
                      >
                        ERASE
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Deployment Modal */}
      {showDeployModal && (
        <div className="fixed inset-0 z-[5000] flex items-center justify-center p-4 md:p-12">
          <div className="absolute inset-0 bg-black/95 backdrop-blur-xl" onClick={() => setShowDeployModal(false)} />
          <div className="relative w-full max-w-5xl h-[80vh] bg-[#080808] border border-white/10 shadow-[0_0_100px_rgba(0,0,0,0.8)] flex flex-col animate-in fade-in zoom-in-95 duration-500">
            <div className="p-6 md:p-10 border-b border-white/5 flex justify-between items-center">
               <div>
                  <h3 className="text-xl md:text-2xl font-black uppercase tracking-[0.3em] text-blue-400">GitHub_Sync_Generator</h3>
                  <p className="text-[9px] opacity-40 uppercase tracking-widest mt-1">Copy code {'->'} Update data/resources.ts {'->'} Push to GitHub</p>
               </div>
               <button onClick={() => setShowDeployModal(false)} className="clickable p-2 opacity-30 hover:opacity-100">
                  <svg width="24" height="24" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path d="M6 18L18 6M6 6l12 12" /></svg>
               </button>
            </div>
            <div className="flex-1 overflow-hidden p-6 md:p-10">
               <div className="h-full w-full bg-black/50 border border-white/5 rounded-sm overflow-y-auto no-scrollbar p-6 font-mono text-[10px] md:text-xs text-white/60 relative">
                  <pre className="whitespace-pre-wrap">{generateDeploymentCode()}</pre>
               </div>
            </div>
            <div className="p-6 md:p-10 border-t border-white/5 flex flex-col md:flex-row gap-6 items-center justify-between">
               <div className="text-[8px] md:text-[9px] opacity-20 uppercase tracking-[0.2em] font-black max-w-sm text-center md:text-left">
                  COMMIT_READY: PASTE THIS OVER "data/resources.ts" AND PUSH TO MASTER BRANCH
               </div>
               <button 
                onClick={copyDeploymentCode}
                className="clickable w-full md:w-auto px-12 py-5 bg-white text-black font-black tracking-[0.8em] uppercase text-[10px] hover:bg-zinc-200 transition-all active:scale-[0.98]"
               >
                 COPY_CODE_FOR_GITHUB
               </button>
            </div>
          </div>
        </div>
      )}
      
      <div className="fixed inset-0 pointer-events-none z-0 opacity-[0.02] bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_4px,4px_100%]" />
      
      <style>{`
        @keyframes shake {
          0%, 100% { transform: translateX(0); }
          25% { transform: translateX(-4px); }
          75% { transform: translateX(4px); }
        }
        .animate-shake {
          animation: shake 0.2s cubic-bezier(.36,.07,.19,.97) both;
        }
      `}</style>
    </div>
  );
};

export default AdminDashboard;