import { Resource, ResourceCategory } from '../types';

/**
 * PRODUCTION ARCHIVE DATA
 * Auto-generated by Resource Forensic Admin Panel
 * Note: 'as any' is used to satisfy TS when enum values are literals in JSON.
 */
const INITIAL_RESOURCES: Resource[] = [
  {
    "category": "Anime Clips",
    "name": "Chainsaw Man - Reze Arc",
    "youtubeId": "OvN4MXnW2Qw",
    "driveUrl": "https://mega.nz/folder/xJciFQJB",
    "getKeyUrl": "https://work.ink/2bBx/anime-forensic-chainsaw-man-reze-arc-clips",
    "description": "Welcome to the ultimate editing resource for Chainsaw Man – The Movie: Reze Arc. We are dedicated to supporting the editing community by providing high-quality, upscaled, and raw clips completely for free.",
    "thumbnail": "https://i.ibb.co/D35KSbc/Ov-N4-MXn-W2-Qw-HD.jpg",
    "id": "res-1768039688845",
    "createdAt": 1768039688845
  }
] as any;

const STORAGE_KEY = 'resource_forensic_vault';

export const getResources = (): Resource[] => {
  const stored = localStorage.getItem(STORAGE_KEY);
  if (!stored) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(INITIAL_RESOURCES));
    return INITIAL_RESOURCES;
  }
  return JSON.parse(stored);
};

export const saveResource = (resource: Resource) => {
  const resources = getResources();
  const updated = [resource, ...resources];
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
};

export const updateResource = (updatedResource: Resource) => {
  const resources = getResources();
  const updated = resources.map(r => r.id === updatedResource.id ? updatedResource : r);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
};

export const deleteResource = (id: string) => {
  const resources = getResources();
  const updated = resources.filter(r => r.id !== id);
  localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
  return updated;
};
